application: kivarecruit
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /tasks/teamData
  script: getTeamData.py
  
- url: /.*
  script: kivarecruit_main.py
