application: kivarecruit
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /tasks/teamData
  script: getTeamData.py
  login: admin
  
- url: /tasks/teamNames
  script: getTeamNames.py
  login: admin
  
- url: /.*
  script: kivarecruit_main.py
